[package]
name = "wasmi-component"
description = "Add the component model to wasmi"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# wasmi = { version = "1.0" }
wasmi = { path = "../../../wasmi/crates/wasmi" }
wasmparser = { version = "0.253.0" }
anyhow = { version = "1.0" }
slotmap = { version = "1.0" }
as-any = { version = "0.3.0" }
