[workspace]
resolver = "2"
members = [
    "crates/wasmi-component",
    "crates/wasmi-component-bindgen",
    "crates/wasmi-component-macros",
    "crates/wasmi-component-macros-impl",
    "crates/wasmi-component-parser",
    "crates/wasmi-component-wasi",

    "examples/component/primitives",
    "examples/component/lists",
    "examples/component/custom_types",
    "examples/wasi/stdio",
]
exclude = ["guests/"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
