[workspace]
resolver = "2"
members = [
    "crates/wasmi-component",
    "crates/wasmi-component-bindgen",
    "crates/wasmi-component-macros",
    "crates/wasmi-component-parser",
    "crates/wasmi-component-wasi",
]
exclude = ["examples/"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
