(component
  (core type (;0;) (func (param i32)))
  (core type (;1;) (func (param i32 i32)))
  (core type (;2;) (func (param i32 i32 i32 i32)))
  (core type (;3;) (func (param i32) (result i32)))
  (core type (;4;) (func (result i32)))
  (core type (;5;) (func (param i32 i32 i32 i32) (result i32)))
  (core type (;6;)
    (module
      (alias outer 1 0 (type (;0;)))
      (import "wasi:io/error@0.2.0" "[resource-drop]error" (func (type 0)))
      (import "wasi:io/poll@0.2.0" "[resource-drop]pollable" (func (type 0)))
      (import "wasi:io/streams@0.2.0" "[resource-drop]input-stream" (func (type 0)))
      (import "wasi:io/streams@0.2.0" "[resource-drop]output-stream" (func (type 0)))
      (import "wasi:cli/terminal-input@0.2.0" "[resource-drop]terminal-input" (func (type 0)))
      (import "wasi:cli/terminal-output@0.2.0" "[resource-drop]terminal-output" (func (type 0)))
      (import "wasi:cli/environment@0.2.0" "get-environment" (func (type 0)))
      (import "wasi:cli/exit@0.2.0" "exit" (func (type 0)))
      (import "wasi:io/poll@0.2.0" "[method]pollable.block" (func (type 0)))
      (alias outer 1 1 (type (;1;)))
      (import "wasi:io/streams@0.2.0" "[method]output-stream.check-write" (func (type 1)))
      (alias outer 1 2 (type (;2;)))
      (import "wasi:io/streams@0.2.0" "[method]output-stream.write" (func (type 2)))
      (import "wasi:io/streams@0.2.0" "[method]output-stream.blocking-flush" (func (type 1)))
      (alias outer 1 3 (type (;3;)))
      (import "wasi:io/streams@0.2.0" "[method]output-stream.subscribe" (func (type 3)))
      (alias outer 1 4 (type (;4;)))
      (import "wasi:cli/stdin@0.2.0" "get-stdin" (func (type 4)))
      (import "wasi:cli/stdout@0.2.0" "get-stdout" (func (type 4)))
      (import "wasi:cli/stderr@0.2.0" "get-stderr" (func (type 4)))
      (import "wasi:cli/terminal-stdin@0.2.0" "get-terminal-stdin" (func (type 0)))
      (import "wasi:cli/terminal-stdout@0.2.0" "get-terminal-stdout" (func (type 0)))
      (import "wasi:cli/terminal-stderr@0.2.0" "get-terminal-stderr" (func (type 0)))
      (export "memory" (memory 17))
      (export "wasmi-component:wasi-examples/exported-funcs@0.1.0#print-stderr" (func (type 1)))
      (export "wasmi-component:wasi-examples/exported-funcs@0.1.0#print-stdout" (func (type 1)))
      (alias outer 1 5 (type (;5;)))
      (export "cabi_realloc" (func (type 5)))
    )
  )
  (core type (;7;)
    (module
      (alias outer 1 1 (type (;0;)))
      (export "0" (func (type 0)))
      (alias outer 1 2 (type (;1;)))
      (export "1" (func (type 1)))
      (export "2" (func (type 0)))
      (alias outer 1 0 (type (;2;)))
      (export "3" (func (type 2)))
      (export "4" (func (type 2)))
      (export "5" (func (type 2)))
      (export "6" (func (type 2)))
      (export "$imports" (table 7 7 funcref))
    )
  )
  (core type (;8;)
    (module
      (alias outer 1 1 (type (;0;)))
      (import "" "0" (func (type 0)))
      (alias outer 1 2 (type (;1;)))
      (import "" "1" (func (type 1)))
      (import "" "2" (func (type 0)))
      (alias outer 1 0 (type (;2;)))
      (import "" "3" (func (type 2)))
      (import "" "4" (func (type 2)))
      (import "" "5" (func (type 2)))
      (import "" "6" (func (type 2)))
      (import "" "$imports" (table 7 7 funcref))
    )
  )
  (import "unbundled-module0" (core module (;0;) (type 6)))
  (import "unbundled-module1" (core module (;1;) (type 7)))
  (import "unbundled-module2" (core module (;2;) (type 8)))
  (type $ty-wasi:io/poll@0.2.6 (;0;)
    (instance
      (export (;0;) "pollable" (type (sub resource)))
      (type (;1;) (borrow 0))
      (type (;2;) (func (param "self" 1)))
      (export (;0;) "[method]pollable.block" (func (type 2)))
    )
  )
  (import "wasi:io/poll@0.2.6" (instance $wasi:io/poll@0.2.6 (;0;) (type $ty-wasi:io/poll@0.2.6)))
  (type $ty-wasi:io/error@0.2.6 (;1;)
    (instance
      (export (;0;) "error" (type (sub resource)))
    )
  )
  (import "wasi:io/error@0.2.6" (instance $wasi:io/error@0.2.6 (;1;) (type $ty-wasi:io/error@0.2.6)))
  (alias export $wasi:io/error@0.2.6 "error" (type $error (;2;)))
  (alias export $wasi:io/poll@0.2.6 "pollable" (type $pollable (;3;)))
  (type $ty-wasi:io/streams@0.2.6 (;4;)
    (instance
      (export (;0;) "input-stream" (type (sub resource)))
      (export (;1;) "output-stream" (type (sub resource)))
      (alias outer 1 $error (type (;2;)))
      (export (;3;) "error" (type (eq 2)))
      (type (;4;) (own 3))
      (type (;5;) (variant (case "last-operation-failed" 4) (case "closed")))
      (export (;6;) "stream-error" (type (eq 5)))
      (alias outer 1 $pollable (type (;7;)))
      (export (;8;) "pollable" (type (eq 7)))
      (type (;9;) (borrow 1))
      (type (;10;) (result u64 (error 6)))
      (type (;11;) (func (param "self" 9) (result 10)))
      (export (;0;) "[method]output-stream.check-write" (func (type 11)))
      (type (;12;) (list u8))
      (type (;13;) (result (error 6)))
      (type (;14;) (func (param "self" 9) (param "contents" 12) (result 13)))
      (export (;1;) "[method]output-stream.write" (func (type 14)))
      (type (;15;) (func (param "self" 9) (result 13)))
      (export (;2;) "[method]output-stream.blocking-flush" (func (type 15)))
      (type (;16;) (own 8))
      (type (;17;) (func (param "self" 9) (result 16)))
      (export (;3;) "[method]output-stream.subscribe" (func (type 17)))
    )
  )
  (import "wasi:io/streams@0.2.6" (instance $wasi:io/streams@0.2.6 (;2;) (type $ty-wasi:io/streams@0.2.6)))
  (type $ty-wasi:cli/environment@0.2.6 (;5;)
    (instance
      (type (;0;) (tuple string string))
      (type (;1;) (list 0))
      (type (;2;) (func (result 1)))
      (export (;0;) "get-environment" (func (type 2)))
    )
  )
  (import "wasi:cli/environment@0.2.6" (instance $wasi:cli/environment@0.2.6 (;3;) (type $ty-wasi:cli/environment@0.2.6)))
  (type $ty-wasi:cli/exit@0.2.6 (;6;)
    (instance
      (type (;0;) (result))
      (type (;1;) (func (param "status" 0)))
      (export (;0;) "exit" (func (type 1)))
    )
  )
  (import "wasi:cli/exit@0.2.6" (instance $wasi:cli/exit@0.2.6 (;4;) (type $ty-wasi:cli/exit@0.2.6)))
  (alias export $wasi:io/streams@0.2.6 "input-stream" (type $input-stream (;7;)))
  (type $ty-wasi:cli/stdin@0.2.6 (;8;)
    (instance
      (alias outer 1 $input-stream (type (;0;)))
      (export (;1;) "input-stream" (type (eq 0)))
      (type (;2;) (own 1))
      (type (;3;) (func (result 2)))
      (export (;0;) "get-stdin" (func (type 3)))
    )
  )
  (import "wasi:cli/stdin@0.2.6" (instance $wasi:cli/stdin@0.2.6 (;5;) (type $ty-wasi:cli/stdin@0.2.6)))
  (alias export $wasi:io/streams@0.2.6 "output-stream" (type $output-stream (;9;)))
  (type $ty-wasi:cli/stdout@0.2.6 (;10;)
    (instance
      (alias outer 1 $output-stream (type (;0;)))
      (export (;1;) "output-stream" (type (eq 0)))
      (type (;2;) (own 1))
      (type (;3;) (func (result 2)))
      (export (;0;) "get-stdout" (func (type 3)))
    )
  )
  (import "wasi:cli/stdout@0.2.6" (instance $wasi:cli/stdout@0.2.6 (;6;) (type $ty-wasi:cli/stdout@0.2.6)))
  (alias export $wasi:io/streams@0.2.6 "output-stream" (type $"#type11 output-stream" (@name "output-stream") (;11;)))
  (type $ty-wasi:cli/stderr@0.2.6 (;12;)
    (instance
      (alias outer 1 $"#type11 output-stream" (type (;0;)))
      (export (;1;) "output-stream" (type (eq 0)))
      (type (;2;) (own 1))
      (type (;3;) (func (result 2)))
      (export (;0;) "get-stderr" (func (type 3)))
    )
  )
  (import "wasi:cli/stderr@0.2.6" (instance $wasi:cli/stderr@0.2.6 (;7;) (type $ty-wasi:cli/stderr@0.2.6)))
  (type $ty-wasi:cli/terminal-input@0.2.6 (;13;)
    (instance
      (export (;0;) "terminal-input" (type (sub resource)))
    )
  )
  (import "wasi:cli/terminal-input@0.2.6" (instance $wasi:cli/terminal-input@0.2.6 (;8;) (type $ty-wasi:cli/terminal-input@0.2.6)))
  (type $ty-wasi:cli/terminal-output@0.2.6 (;14;)
    (instance
      (export (;0;) "terminal-output" (type (sub resource)))
    )
  )
  (import "wasi:cli/terminal-output@0.2.6" (instance $wasi:cli/terminal-output@0.2.6 (;9;) (type $ty-wasi:cli/terminal-output@0.2.6)))
  (alias export $wasi:cli/terminal-input@0.2.6 "terminal-input" (type $terminal-input (;15;)))
  (type $ty-wasi:cli/terminal-stdin@0.2.6 (;16;)
    (instance
      (alias outer 1 $terminal-input (type (;0;)))
      (export (;1;) "terminal-input" (type (eq 0)))
      (type (;2;) (own 1))
      (type (;3;) (option 2))
      (type (;4;) (func (result 3)))
      (export (;0;) "get-terminal-stdin" (func (type 4)))
    )
  )
  (import "wasi:cli/terminal-stdin@0.2.6" (instance $wasi:cli/terminal-stdin@0.2.6 (;10;) (type $ty-wasi:cli/terminal-stdin@0.2.6)))
  (alias export $wasi:cli/terminal-output@0.2.6 "terminal-output" (type $terminal-output (;17;)))
  (type $ty-wasi:cli/terminal-stdout@0.2.6 (;18;)
    (instance
      (alias outer 1 $terminal-output (type (;0;)))
      (export (;1;) "terminal-output" (type (eq 0)))
      (type (;2;) (own 1))
      (type (;3;) (option 2))
      (type (;4;) (func (result 3)))
      (export (;0;) "get-terminal-stdout" (func (type 4)))
    )
  )
  (import "wasi:cli/terminal-stdout@0.2.6" (instance $wasi:cli/terminal-stdout@0.2.6 (;11;) (type $ty-wasi:cli/terminal-stdout@0.2.6)))
  (alias export $wasi:cli/terminal-output@0.2.6 "terminal-output" (type $"#type19 terminal-output" (@name "terminal-output") (;19;)))
  (type $ty-wasi:cli/terminal-stderr@0.2.6 (;20;)
    (instance
      (alias outer 1 $"#type19 terminal-output" (type (;0;)))
      (export (;1;) "terminal-output" (type (eq 0)))
      (type (;2;) (own 1))
      (type (;3;) (option 2))
      (type (;4;) (func (result 3)))
      (export (;0;) "get-terminal-stderr" (func (type 4)))
    )
  )
  (import "wasi:cli/terminal-stderr@0.2.6" (instance $wasi:cli/terminal-stderr@0.2.6 (;12;) (type $ty-wasi:cli/terminal-stderr@0.2.6)))
  (alias outer 0 0 (core module $main (;3;)))
  (alias outer 0 1 (core module $wit-component-shim-module (;4;)))
  (alias outer 0 2 (core module $wit-component-fixup (;5;)))
  (core instance $wit-component-shim-instance (;0;) (instantiate $wit-component-shim-module))
  (alias export $wasi:io/error@0.2.6 "error" (type $"#type21 error" (@name "error") (;21;)))
  (core func $resource.drop (;0;) (canon resource.drop $"#type21 error"))
  (core instance $wasi:io/error@0.2.0 (;1;)
    (export "[resource-drop]error" (func $resource.drop))
  )
  (alias export $wasi:io/poll@0.2.6 "pollable" (type $"#type22 pollable" (@name "pollable") (;22;)))
  (core func $"#core-func1 resource.drop" (@name "resource.drop") (;1;) (canon resource.drop $"#type22 pollable"))
  (alias export $wasi:io/poll@0.2.6 "[method]pollable.block" (func $"[method]pollable.block" (;0;)))
  (core func $"[method]pollable.block" (;2;) (canon lower (func $"[method]pollable.block")))
  (core instance $wasi:io/poll@0.2.0 (;2;)
    (export "[resource-drop]pollable" (func $"#core-func1 resource.drop"))
    (export "[method]pollable.block" (func $"[method]pollable.block"))
  )
  (alias export $wasi:io/streams@0.2.6 "input-stream" (type $"#type23 input-stream" (@name "input-stream") (;23;)))
  (core func $"#core-func3 resource.drop" (@name "resource.drop") (;3;) (canon resource.drop $"#type23 input-stream"))
  (alias export $wasi:io/streams@0.2.6 "output-stream" (type $"#type24 output-stream" (@name "output-stream") (;24;)))
  (core func $"#core-func4 resource.drop" (@name "resource.drop") (;4;) (canon resource.drop $"#type24 output-stream"))
  (alias core export $wit-component-shim-instance "0" (core func $"indirect-wasi:io/streams@0.2.0-[method]output-stream.check-write" (;5;)))
  (alias core export $wit-component-shim-instance "1" (core func $"indirect-wasi:io/streams@0.2.0-[method]output-stream.write" (;6;)))
  (alias core export $wit-component-shim-instance "2" (core func $"indirect-wasi:io/streams@0.2.0-[method]output-stream.blocking-flush" (;7;)))
  (alias export $wasi:io/streams@0.2.6 "[method]output-stream.subscribe" (func $"[method]output-stream.subscribe" (;1;)))
  (core func $"[method]output-stream.subscribe" (;8;) (canon lower (func $"[method]output-stream.subscribe")))
  (core instance $wasi:io/streams@0.2.0 (;3;)
    (export "[resource-drop]input-stream" (func $"#core-func3 resource.drop"))
    (export "[resource-drop]output-stream" (func $"#core-func4 resource.drop"))
    (export "[method]output-stream.check-write" (func $"indirect-wasi:io/streams@0.2.0-[method]output-stream.check-write"))
    (export "[method]output-stream.write" (func $"indirect-wasi:io/streams@0.2.0-[method]output-stream.write"))
    (export "[method]output-stream.blocking-flush" (func $"indirect-wasi:io/streams@0.2.0-[method]output-stream.blocking-flush"))
    (export "[method]output-stream.subscribe" (func $"[method]output-stream.subscribe"))
  )
  (alias export $wasi:cli/terminal-input@0.2.6 "terminal-input" (type $"#type25 terminal-input" (@name "terminal-input") (;25;)))
  (core func $"#core-func9 resource.drop" (@name "resource.drop") (;9;) (canon resource.drop $"#type25 terminal-input"))
  (core instance $wasi:cli/terminal-input@0.2.0 (;4;)
    (export "[resource-drop]terminal-input" (func $"#core-func9 resource.drop"))
  )
  (alias export $wasi:cli/terminal-output@0.2.6 "terminal-output" (type $"#type26 terminal-output" (@name "terminal-output") (;26;)))
  (core func $"#core-func10 resource.drop" (@name "resource.drop") (;10;) (canon resource.drop $"#type26 terminal-output"))
  (core instance $wasi:cli/terminal-output@0.2.0 (;5;)
    (export "[resource-drop]terminal-output" (func $"#core-func10 resource.drop"))
  )
  (alias core export $wit-component-shim-instance "3" (core func $indirect-wasi:cli/environment@0.2.0-get-environment (;11;)))
  (core instance $wasi:cli/environment@0.2.0 (;6;)
    (export "get-environment" (func $indirect-wasi:cli/environment@0.2.0-get-environment))
  )
  (alias export $wasi:cli/exit@0.2.6 "exit" (func $exit (;2;)))
  (core func $exit (;12;) (canon lower (func $exit)))
  (core instance $wasi:cli/exit@0.2.0 (;7;)
    (export "exit" (func $exit))
  )
  (alias export $wasi:cli/stdin@0.2.6 "get-stdin" (func $get-stdin (;3;)))
  (core func $get-stdin (;13;) (canon lower (func $get-stdin)))
  (core instance $wasi:cli/stdin@0.2.0 (;8;)
    (export "get-stdin" (func $get-stdin))
  )
  (alias export $wasi:cli/stdout@0.2.6 "get-stdout" (func $get-stdout (;4;)))
  (core func $get-stdout (;14;) (canon lower (func $get-stdout)))
  (core instance $wasi:cli/stdout@0.2.0 (;9;)
    (export "get-stdout" (func $get-stdout))
  )
  (alias export $wasi:cli/stderr@0.2.6 "get-stderr" (func $get-stderr (;5;)))
  (core func $get-stderr (;15;) (canon lower (func $get-stderr)))
  (core instance $wasi:cli/stderr@0.2.0 (;10;)
    (export "get-stderr" (func $get-stderr))
  )
  (alias core export $wit-component-shim-instance "4" (core func $indirect-wasi:cli/terminal-stdin@0.2.0-get-terminal-stdin (;16;)))
  (core instance $wasi:cli/terminal-stdin@0.2.0 (;11;)
    (export "get-terminal-stdin" (func $indirect-wasi:cli/terminal-stdin@0.2.0-get-terminal-stdin))
  )
  (alias core export $wit-component-shim-instance "5" (core func $indirect-wasi:cli/terminal-stdout@0.2.0-get-terminal-stdout (;17;)))
  (core instance $wasi:cli/terminal-stdout@0.2.0 (;12;)
    (export "get-terminal-stdout" (func $indirect-wasi:cli/terminal-stdout@0.2.0-get-terminal-stdout))
  )
  (alias core export $wit-component-shim-instance "6" (core func $indirect-wasi:cli/terminal-stderr@0.2.0-get-terminal-stderr (;18;)))
  (core instance $wasi:cli/terminal-stderr@0.2.0 (;13;)
    (export "get-terminal-stderr" (func $indirect-wasi:cli/terminal-stderr@0.2.0-get-terminal-stderr))
  )
  (core instance $main (;14;) (instantiate $main
      (with "wasi:io/error@0.2.0" (instance $wasi:io/error@0.2.0))
      (with "wasi:io/poll@0.2.0" (instance $wasi:io/poll@0.2.0))
      (with "wasi:io/streams@0.2.0" (instance $wasi:io/streams@0.2.0))
      (with "wasi:cli/terminal-input@0.2.0" (instance $wasi:cli/terminal-input@0.2.0))
      (with "wasi:cli/terminal-output@0.2.0" (instance $wasi:cli/terminal-output@0.2.0))
      (with "wasi:cli/environment@0.2.0" (instance $wasi:cli/environment@0.2.0))
      (with "wasi:cli/exit@0.2.0" (instance $wasi:cli/exit@0.2.0))
      (with "wasi:cli/stdin@0.2.0" (instance $wasi:cli/stdin@0.2.0))
      (with "wasi:cli/stdout@0.2.0" (instance $wasi:cli/stdout@0.2.0))
      (with "wasi:cli/stderr@0.2.0" (instance $wasi:cli/stderr@0.2.0))
      (with "wasi:cli/terminal-stdin@0.2.0" (instance $wasi:cli/terminal-stdin@0.2.0))
      (with "wasi:cli/terminal-stdout@0.2.0" (instance $wasi:cli/terminal-stdout@0.2.0))
      (with "wasi:cli/terminal-stderr@0.2.0" (instance $wasi:cli/terminal-stderr@0.2.0))
    )
  )
  (alias core export $main "memory" (core memory $memory (;0;)))
  (alias core export $wit-component-shim-instance "$imports" (core table $"shim table" (;0;)))
  (alias export $wasi:io/streams@0.2.6 "[method]output-stream.check-write" (func $"[method]output-stream.check-write" (;6;)))
  (alias core export $main "cabi_realloc" (core func $realloc (;19;)))
  (core func $"#core-func20 indirect-wasi:io/streams@0.2.0-[method]output-stream.check-write" (@name "indirect-wasi:io/streams@0.2.0-[method]output-stream.check-write") (;20;) (canon lower (func $"[method]output-stream.check-write") (memory $memory)))
  (alias export $wasi:io/streams@0.2.6 "[method]output-stream.write" (func $"[method]output-stream.write" (;7;)))
  (core func $"#core-func21 indirect-wasi:io/streams@0.2.0-[method]output-stream.write" (@name "indirect-wasi:io/streams@0.2.0-[method]output-stream.write") (;21;) (canon lower (func $"[method]output-stream.write") (memory $memory)))
  (alias export $wasi:io/streams@0.2.6 "[method]output-stream.blocking-flush" (func $"[method]output-stream.blocking-flush" (;8;)))
  (core func $"#core-func22 indirect-wasi:io/streams@0.2.0-[method]output-stream.blocking-flush" (@name "indirect-wasi:io/streams@0.2.0-[method]output-stream.blocking-flush") (;22;) (canon lower (func $"[method]output-stream.blocking-flush") (memory $memory)))
  (alias export $wasi:cli/environment@0.2.6 "get-environment" (func $get-environment (;9;)))
  (core func $"#core-func23 indirect-wasi:cli/environment@0.2.0-get-environment" (@name "indirect-wasi:cli/environment@0.2.0-get-environment") (;23;) (canon lower (func $get-environment) (memory $memory) (realloc $realloc) string-encoding=utf8))
  (alias export $wasi:cli/terminal-stdin@0.2.6 "get-terminal-stdin" (func $get-terminal-stdin (;10;)))
  (core func $"#core-func24 indirect-wasi:cli/terminal-stdin@0.2.0-get-terminal-stdin" (@name "indirect-wasi:cli/terminal-stdin@0.2.0-get-terminal-stdin") (;24;) (canon lower (func $get-terminal-stdin) (memory $memory)))
  (alias export $wasi:cli/terminal-stdout@0.2.6 "get-terminal-stdout" (func $get-terminal-stdout (;11;)))
  (core func $"#core-func25 indirect-wasi:cli/terminal-stdout@0.2.0-get-terminal-stdout" (@name "indirect-wasi:cli/terminal-stdout@0.2.0-get-terminal-stdout") (;25;) (canon lower (func $get-terminal-stdout) (memory $memory)))
  (alias export $wasi:cli/terminal-stderr@0.2.6 "get-terminal-stderr" (func $get-terminal-stderr (;12;)))
  (core func $"#core-func26 indirect-wasi:cli/terminal-stderr@0.2.0-get-terminal-stderr" (@name "indirect-wasi:cli/terminal-stderr@0.2.0-get-terminal-stderr") (;26;) (canon lower (func $get-terminal-stderr) (memory $memory)))
  (core instance $fixup-args (;15;)
    (export "$imports" (table $"shim table"))
    (export "0" (func $"#core-func20 indirect-wasi:io/streams@0.2.0-[method]output-stream.check-write"))
    (export "1" (func $"#core-func21 indirect-wasi:io/streams@0.2.0-[method]output-stream.write"))
    (export "2" (func $"#core-func22 indirect-wasi:io/streams@0.2.0-[method]output-stream.blocking-flush"))
    (export "3" (func $"#core-func23 indirect-wasi:cli/environment@0.2.0-get-environment"))
    (export "4" (func $"#core-func24 indirect-wasi:cli/terminal-stdin@0.2.0-get-terminal-stdin"))
    (export "5" (func $"#core-func25 indirect-wasi:cli/terminal-stdout@0.2.0-get-terminal-stdout"))
    (export "6" (func $"#core-func26 indirect-wasi:cli/terminal-stderr@0.2.0-get-terminal-stderr"))
  )
  (core instance $fixup (;16;) (instantiate $wit-component-fixup
      (with "" (instance $fixup-args))
    )
  )
  (type (;27;) (func (param "text" string)))
  (alias core export $main "wasmi-component:wasi-examples/exported-funcs@0.1.0#print-stdout" (core func $wasmi-component:wasi-examples/exported-funcs@0.1.0#print-stdout (;27;)))
  (func $print-stdout (;13;) (type 27) (canon lift (core func $wasmi-component:wasi-examples/exported-funcs@0.1.0#print-stdout) (memory $memory) (realloc $realloc) string-encoding=utf8))
  (alias core export $main "wasmi-component:wasi-examples/exported-funcs@0.1.0#print-stderr" (core func $wasmi-component:wasi-examples/exported-funcs@0.1.0#print-stderr (;28;)))
  (func $print-stderr (;14;) (type 27) (canon lift (core func $wasmi-component:wasi-examples/exported-funcs@0.1.0#print-stderr) (memory $memory) (realloc $realloc) string-encoding=utf8))
  (component $wasmi-component:wasi-examples/exported-funcs@0.1.0-shim-component (;0;)
    (type (;0;) (func (param "text" string)))
    (import "import-func-print-stdout" (func (;0;) (type 0)))
    (import "import-func-print-stderr" (func (;1;) (type 0)))
    (type (;1;) (func (param "text" string)))
    (export (;2;) "print-stdout" (func 0) (func (type 1)))
    (export (;3;) "print-stderr" (func 1) (func (type 1)))
  )
  (instance $wasmi-component:wasi-examples/exported-funcs@0.1.0-shim-instance (;13;) (instantiate $wasmi-component:wasi-examples/exported-funcs@0.1.0-shim-component
      (with "import-func-print-stdout" (func $print-stdout))
      (with "import-func-print-stderr" (func $print-stderr))
    )
  )
  (export $wasmi-component:wasi-examples/exported-funcs@0.1.0 (;14;) "wasmi-component:wasi-examples/exported-funcs@0.1.0" (instance $wasmi-component:wasi-examples/exported-funcs@0.1.0-shim-instance))
  (@producers
    (processed-by "wit-component" "0.246.2")
  )
)
