package wasmi-component:component-examples@0.1.0;

interface round-trip {
    record person {
        id: u64,
        name: string,
    }

    variant data {
        number(f64),
        text(string),
    }

    trip-person: func(value: person) -> person;

    trip-data: func(value: data) -> data;
}

world test-example {
    import round-trip;

    export round-trip;

    import log: func(message: string);
}
