(component $wasmi-component-example-guest
  (core type (;0;) (func (param i32 i32)))
  (core type (;1;) (func (param i32 i32 i32)))
  (core type (;2;) (func (param i32)))
  (core type (;3;) (func (param i32 i32) (result i32)))
  (core type (;4;) (func (param i32 i32 i32 i32) (result i32)))
  (core type (;5;)
    (module
      (alias outer $wasmi-component-example-guest 0 (type (;0;)))
      (import "$root" "log" (func (type 0)))
      (alias outer $wasmi-component-example-guest 1 (type (;1;)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "list-string" (func (type 1)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "list-s8" (func (type 1)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "list-u8" (func (type 1)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "list-f32" (func (type 1)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "list-f64" (func (type 1)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "list-s16" (func (type 1)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "list-s32" (func (type 1)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "list-s64" (func (type 1)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "list-u16" (func (type 1)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "list-u32" (func (type 1)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "list-u64" (func (type 1)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "list-bool" (func (type 1)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "list-char" (func (type 1)))
      (export "memory" (memory 17))
      (alias outer $wasmi-component-example-guest 2 (type (;2;)))
      (export "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-bool" (func (type 2)))
      (export "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-char" (func (type 2)))
      (export "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-f32" (func (type 2)))
      (export "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-f64" (func (type 2)))
      (export "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-s16" (func (type 2)))
      (export "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-s32" (func (type 2)))
      (export "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-s64" (func (type 2)))
      (export "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-s8" (func (type 2)))
      (export "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-string" (func (type 2)))
      (export "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-u16" (func (type 2)))
      (export "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-u32" (func (type 2)))
      (export "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-u64" (func (type 2)))
      (export "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-u8" (func (type 2)))
      (alias outer $wasmi-component-example-guest 3 (type (;3;)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#list-bool" (func (type 3)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#list-char" (func (type 3)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#list-f32" (func (type 3)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#list-f64" (func (type 3)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#list-s16" (func (type 3)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#list-s32" (func (type 3)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#list-s64" (func (type 3)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#list-s8" (func (type 3)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#list-string" (func (type 3)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#list-u16" (func (type 3)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#list-u32" (func (type 3)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#list-u64" (func (type 3)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#list-u8" (func (type 3)))
      (alias outer $wasmi-component-example-guest 4 (type (;4;)))
      (export "cabi_realloc_wit_bindgen_0_58_0" (func (type 4)))
      (export "cabi_realloc" (func (type 4)))
      (export "__data_end" (global i32))
      (export "__heap_base" (global i32))
    )
  )
  (core type (;6;)
    (module
      (alias outer $wasmi-component-example-guest 0 (type (;0;)))
      (export "0" (func (type 0)))
      (alias outer $wasmi-component-example-guest 1 (type (;1;)))
      (export "1" (func (type 1)))
      (export "2" (func (type 1)))
      (export "3" (func (type 1)))
      (export "4" (func (type 1)))
      (export "5" (func (type 1)))
      (export "6" (func (type 1)))
      (export "7" (func (type 1)))
      (export "8" (func (type 1)))
      (export "9" (func (type 1)))
      (export "10" (func (type 1)))
      (export "11" (func (type 1)))
      (export "12" (func (type 1)))
      (export "13" (func (type 1)))
      (export "$imports" (table 14 14 funcref))
    )
  )
  (core type (;7;)
    (module
      (alias outer $wasmi-component-example-guest 0 (type (;0;)))
      (import "" "0" (func (type 0)))
      (alias outer $wasmi-component-example-guest 1 (type (;1;)))
      (import "" "1" (func (type 1)))
      (import "" "2" (func (type 1)))
      (import "" "3" (func (type 1)))
      (import "" "4" (func (type 1)))
      (import "" "5" (func (type 1)))
      (import "" "6" (func (type 1)))
      (import "" "7" (func (type 1)))
      (import "" "8" (func (type 1)))
      (import "" "9" (func (type 1)))
      (import "" "10" (func (type 1)))
      (import "" "11" (func (type 1)))
      (import "" "12" (func (type 1)))
      (import "" "13" (func (type 1)))
      (import "" "$imports" (table 14 14 funcref))
    )
  )
  (import "unbundled-module0" (core module (;0;) (type 5)))
  (import "unbundled-module1" (core module (;1;) (type 6)))
  (import "unbundled-module2" (core module (;2;) (type 7)))
  (type (;0;)
    (instance
      (type (;0;) (list s8))
      (type (;1;) (func (param "value" 0) (result 0)))
      (export (;0;) "list-s8" (func (type 1)))
      (type (;2;) (list s16))
      (type (;3;) (func (param "value" 2) (result 2)))
      (export (;1;) "list-s16" (func (type 3)))
      (type (;4;) (list s32))
      (type (;5;) (func (param "value" 4) (result 4)))
      (export (;2;) "list-s32" (func (type 5)))
      (type (;6;) (list s64))
      (type (;7;) (func (param "value" 6) (result 6)))
      (export (;3;) "list-s64" (func (type 7)))
      (type (;8;) (list u8))
      (type (;9;) (func (param "value" 8) (result 8)))
      (export (;4;) "list-u8" (func (type 9)))
      (type (;10;) (list u16))
      (type (;11;) (func (param "value" 10) (result 10)))
      (export (;5;) "list-u16" (func (type 11)))
      (type (;12;) (list u32))
      (type (;13;) (func (param "value" 12) (result 12)))
      (export (;6;) "list-u32" (func (type 13)))
      (type (;14;) (list u64))
      (type (;15;) (func (param "value" 14) (result 14)))
      (export (;7;) "list-u64" (func (type 15)))
      (type (;16;) (list f32))
      (type (;17;) (func (param "value" 16) (result 16)))
      (export (;8;) "list-f32" (func (type 17)))
      (type (;18;) (list f64))
      (type (;19;) (func (param "value" 18) (result 18)))
      (export (;9;) "list-f64" (func (type 19)))
      (type (;20;) (list bool))
      (type (;21;) (func (param "value" 20) (result 20)))
      (export (;10;) "list-bool" (func (type 21)))
      (type (;22;) (list char))
      (type (;23;) (func (param "value" 22) (result 22)))
      (export (;11;) "list-char" (func (type 23)))
      (type (;24;) (list string))
      (type (;25;) (func (param "value" 24) (result 24)))
      (export (;12;) "list-string" (func (type 25)))
    )
  )
  (import "wasmi-component:component-examples/round-trip@0.1.0" (instance (;0;) (type 0)))
  (type (;1;) (func (param "message" string)))
  (import "log" (func (;0;) (type 1)))
  (alias outer $wasmi-component-example-guest 0 (core module (;3;)))
  (alias outer $wasmi-component-example-guest 1 (core module (;4;)))
  (alias outer $wasmi-component-example-guest 2 (core module (;5;)))
  (core instance (;0;) (instantiate 4))
  (alias core export 0 "0" (core func (;0;)))
  (core instance (;1;)
    (export "log" (func 0))
  )
  (alias core export 0 "1" (core func (;1;)))
  (alias core export 0 "2" (core func (;2;)))
  (alias core export 0 "3" (core func (;3;)))
  (alias core export 0 "4" (core func (;4;)))
  (alias core export 0 "5" (core func (;5;)))
  (alias core export 0 "6" (core func (;6;)))
  (alias core export 0 "7" (core func (;7;)))
  (alias core export 0 "8" (core func (;8;)))
  (alias core export 0 "9" (core func (;9;)))
  (alias core export 0 "10" (core func (;10;)))
  (alias core export 0 "11" (core func (;11;)))
  (alias core export 0 "12" (core func (;12;)))
  (alias core export 0 "13" (core func (;13;)))
  (core instance (;2;)
    (export "list-string" (func 1))
    (export "list-s8" (func 2))
    (export "list-u8" (func 3))
    (export "list-f32" (func 4))
    (export "list-f64" (func 5))
    (export "list-s16" (func 6))
    (export "list-s32" (func 7))
    (export "list-s64" (func 8))
    (export "list-u16" (func 9))
    (export "list-u32" (func 10))
    (export "list-u64" (func 11))
    (export "list-bool" (func 12))
    (export "list-char" (func 13))
  )
  (core instance (;3;) (instantiate 3
      (with "$root" (instance 1))
      (with "wasmi-component:component-examples/round-trip@0.1.0" (instance 2))
    )
  )
  (alias core export 3 "memory" (core memory (;0;)))
  (alias core export 0 "$imports" (core table (;0;)))
  (alias core export 3 "cabi_realloc" (core func (;14;)))
  (core func (;15;) (canon lower (func 0) (memory 0) string-encoding=utf8))
  (alias export 0 "list-string" (func (;1;)))
  (core func (;16;) (canon lower (func 1) (memory 0) (realloc 14) string-encoding=utf8))
  (alias export 0 "list-s8" (func (;2;)))
  (core func (;17;) (canon lower (func 2) (memory 0) (realloc 14)))
  (alias export 0 "list-u8" (func (;3;)))
  (core func (;18;) (canon lower (func 3) (memory 0) (realloc 14)))
  (alias export 0 "list-f32" (func (;4;)))
  (core func (;19;) (canon lower (func 4) (memory 0) (realloc 14)))
  (alias export 0 "list-f64" (func (;5;)))
  (core func (;20;) (canon lower (func 5) (memory 0) (realloc 14)))
  (alias export 0 "list-s16" (func (;6;)))
  (core func (;21;) (canon lower (func 6) (memory 0) (realloc 14)))
  (alias export 0 "list-s32" (func (;7;)))
  (core func (;22;) (canon lower (func 7) (memory 0) (realloc 14)))
  (alias export 0 "list-s64" (func (;8;)))
  (core func (;23;) (canon lower (func 8) (memory 0) (realloc 14)))
  (alias export 0 "list-u16" (func (;9;)))
  (core func (;24;) (canon lower (func 9) (memory 0) (realloc 14)))
  (alias export 0 "list-u32" (func (;10;)))
  (core func (;25;) (canon lower (func 10) (memory 0) (realloc 14)))
  (alias export 0 "list-u64" (func (;11;)))
  (core func (;26;) (canon lower (func 11) (memory 0) (realloc 14)))
  (alias export 0 "list-bool" (func (;12;)))
  (core func (;27;) (canon lower (func 12) (memory 0) (realloc 14)))
  (alias export 0 "list-char" (func (;13;)))
  (core func (;28;) (canon lower (func 13) (memory 0) (realloc 14)))
  (core instance (;4;)
    (export "$imports" (table 0))
    (export "0" (func 15))
    (export "1" (func 16))
    (export "2" (func 17))
    (export "3" (func 18))
    (export "4" (func 19))
    (export "5" (func 20))
    (export "6" (func 21))
    (export "7" (func 22))
    (export "8" (func 23))
    (export "9" (func 24))
    (export "10" (func 25))
    (export "11" (func 26))
    (export "12" (func 27))
    (export "13" (func 28))
  )
  (core instance (;5;) (instantiate 5
      (with "" (instance 4))
    )
  )
  (type (;2;) (list s8))
  (type (;3;) (func (param "value" 2) (result 2)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#list-s8" (core func (;29;)))
  (alias core export 3 "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-s8" (core func (;30;)))
  (func (;14;) (type 3) (canon lift (core func 29) (memory 0) (realloc 14) (post-return 30)))
  (type (;4;) (list s16))
  (type (;5;) (func (param "value" 4) (result 4)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#list-s16" (core func (;31;)))
  (alias core export 3 "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-s16" (core func (;32;)))
  (func (;15;) (type 5) (canon lift (core func 31) (memory 0) (realloc 14) (post-return 32)))
  (type (;6;) (list s32))
  (type (;7;) (func (param "value" 6) (result 6)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#list-s32" (core func (;33;)))
  (alias core export 3 "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-s32" (core func (;34;)))
  (func (;16;) (type 7) (canon lift (core func 33) (memory 0) (realloc 14) (post-return 34)))
  (type (;8;) (list s64))
  (type (;9;) (func (param "value" 8) (result 8)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#list-s64" (core func (;35;)))
  (alias core export 3 "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-s64" (core func (;36;)))
  (func (;17;) (type 9) (canon lift (core func 35) (memory 0) (realloc 14) (post-return 36)))
  (type (;10;) (list u8))
  (type (;11;) (func (param "value" 10) (result 10)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#list-u8" (core func (;37;)))
  (alias core export 3 "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-u8" (core func (;38;)))
  (func (;18;) (type 11) (canon lift (core func 37) (memory 0) (realloc 14) (post-return 38)))
  (type (;12;) (list u16))
  (type (;13;) (func (param "value" 12) (result 12)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#list-u16" (core func (;39;)))
  (alias core export 3 "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-u16" (core func (;40;)))
  (func (;19;) (type 13) (canon lift (core func 39) (memory 0) (realloc 14) (post-return 40)))
  (type (;14;) (list u32))
  (type (;15;) (func (param "value" 14) (result 14)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#list-u32" (core func (;41;)))
  (alias core export 3 "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-u32" (core func (;42;)))
  (func (;20;) (type 15) (canon lift (core func 41) (memory 0) (realloc 14) (post-return 42)))
  (type (;16;) (list u64))
  (type (;17;) (func (param "value" 16) (result 16)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#list-u64" (core func (;43;)))
  (alias core export 3 "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-u64" (core func (;44;)))
  (func (;21;) (type 17) (canon lift (core func 43) (memory 0) (realloc 14) (post-return 44)))
  (type (;18;) (list f32))
  (type (;19;) (func (param "value" 18) (result 18)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#list-f32" (core func (;45;)))
  (alias core export 3 "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-f32" (core func (;46;)))
  (func (;22;) (type 19) (canon lift (core func 45) (memory 0) (realloc 14) (post-return 46)))
  (type (;20;) (list f64))
  (type (;21;) (func (param "value" 20) (result 20)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#list-f64" (core func (;47;)))
  (alias core export 3 "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-f64" (core func (;48;)))
  (func (;23;) (type 21) (canon lift (core func 47) (memory 0) (realloc 14) (post-return 48)))
  (type (;22;) (list bool))
  (type (;23;) (func (param "value" 22) (result 22)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#list-bool" (core func (;49;)))
  (alias core export 3 "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-bool" (core func (;50;)))
  (func (;24;) (type 23) (canon lift (core func 49) (memory 0) (realloc 14) (post-return 50)))
  (type (;24;) (list char))
  (type (;25;) (func (param "value" 24) (result 24)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#list-char" (core func (;51;)))
  (alias core export 3 "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-char" (core func (;52;)))
  (func (;25;) (type 25) (canon lift (core func 51) (memory 0) (realloc 14) (post-return 52)))
  (type (;26;) (list string))
  (type (;27;) (func (param "value" 26) (result 26)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#list-string" (core func (;53;)))
  (alias core export 3 "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-string" (core func (;54;)))
  (func (;26;) (type 27) (canon lift (core func 53) (memory 0) (realloc 14) string-encoding=utf8 (post-return 54)))
  (component (;0;)
    (type (;0;) (list s8))
    (type (;1;) (func (param "value" 0) (result 0)))
    (import "import-func-list-s8" (func (;0;) (type 1)))
    (type (;2;) (list s16))
    (type (;3;) (func (param "value" 2) (result 2)))
    (import "import-func-list-s16" (func (;1;) (type 3)))
    (type (;4;) (list s32))
    (type (;5;) (func (param "value" 4) (result 4)))
    (import "import-func-list-s32" (func (;2;) (type 5)))
    (type (;6;) (list s64))
    (type (;7;) (func (param "value" 6) (result 6)))
    (import "import-func-list-s64" (func (;3;) (type 7)))
    (type (;8;) (list u8))
    (type (;9;) (func (param "value" 8) (result 8)))
    (import "import-func-list-u8" (func (;4;) (type 9)))
    (type (;10;) (list u16))
    (type (;11;) (func (param "value" 10) (result 10)))
    (import "import-func-list-u16" (func (;5;) (type 11)))
    (type (;12;) (list u32))
    (type (;13;) (func (param "value" 12) (result 12)))
    (import "import-func-list-u32" (func (;6;) (type 13)))
    (type (;14;) (list u64))
    (type (;15;) (func (param "value" 14) (result 14)))
    (import "import-func-list-u64" (func (;7;) (type 15)))
    (type (;16;) (list f32))
    (type (;17;) (func (param "value" 16) (result 16)))
    (import "import-func-list-f32" (func (;8;) (type 17)))
    (type (;18;) (list f64))
    (type (;19;) (func (param "value" 18) (result 18)))
    (import "import-func-list-f64" (func (;9;) (type 19)))
    (type (;20;) (list bool))
    (type (;21;) (func (param "value" 20) (result 20)))
    (import "import-func-list-bool" (func (;10;) (type 21)))
    (type (;22;) (list char))
    (type (;23;) (func (param "value" 22) (result 22)))
    (import "import-func-list-char" (func (;11;) (type 23)))
    (type (;24;) (list string))
    (type (;25;) (func (param "value" 24) (result 24)))
    (import "import-func-list-string" (func (;12;) (type 25)))
    (type (;26;) (list s8))
    (type (;27;) (func (param "value" 26) (result 26)))
    (export (;13;) "list-s8" (func 0) (func (type 27)))
    (type (;28;) (list s16))
    (type (;29;) (func (param "value" 28) (result 28)))
    (export (;14;) "list-s16" (func 1) (func (type 29)))
    (type (;30;) (list s32))
    (type (;31;) (func (param "value" 30) (result 30)))
    (export (;15;) "list-s32" (func 2) (func (type 31)))
    (type (;32;) (list s64))
    (type (;33;) (func (param "value" 32) (result 32)))
    (export (;16;) "list-s64" (func 3) (func (type 33)))
    (type (;34;) (list u8))
    (type (;35;) (func (param "value" 34) (result 34)))
    (export (;17;) "list-u8" (func 4) (func (type 35)))
    (type (;36;) (list u16))
    (type (;37;) (func (param "value" 36) (result 36)))
    (export (;18;) "list-u16" (func 5) (func (type 37)))
    (type (;38;) (list u32))
    (type (;39;) (func (param "value" 38) (result 38)))
    (export (;19;) "list-u32" (func 6) (func (type 39)))
    (type (;40;) (list u64))
    (type (;41;) (func (param "value" 40) (result 40)))
    (export (;20;) "list-u64" (func 7) (func (type 41)))
    (type (;42;) (list f32))
    (type (;43;) (func (param "value" 42) (result 42)))
    (export (;21;) "list-f32" (func 8) (func (type 43)))
    (type (;44;) (list f64))
    (type (;45;) (func (param "value" 44) (result 44)))
    (export (;22;) "list-f64" (func 9) (func (type 45)))
    (type (;46;) (list bool))
    (type (;47;) (func (param "value" 46) (result 46)))
    (export (;23;) "list-bool" (func 10) (func (type 47)))
    (type (;48;) (list char))
    (type (;49;) (func (param "value" 48) (result 48)))
    (export (;24;) "list-char" (func 11) (func (type 49)))
    (type (;50;) (list string))
    (type (;51;) (func (param "value" 50) (result 50)))
    (export (;25;) "list-string" (func 12) (func (type 51)))
  )
  (instance (;1;) (instantiate 0
      (with "import-func-list-s8" (func 14))
      (with "import-func-list-s16" (func 15))
      (with "import-func-list-s32" (func 16))
      (with "import-func-list-s64" (func 17))
      (with "import-func-list-u8" (func 18))
      (with "import-func-list-u16" (func 19))
      (with "import-func-list-u32" (func 20))
      (with "import-func-list-u64" (func 21))
      (with "import-func-list-f32" (func 22))
      (with "import-func-list-f64" (func 23))
      (with "import-func-list-bool" (func 24))
      (with "import-func-list-char" (func 25))
      (with "import-func-list-string" (func 26))
    )
  )
  (export (;2;) "wasmi-component:component-examples/round-trip@0.1.0" (instance 1))
  (@producers
    (processed-by "wit-component" "0.227.1")
    (processed-by "cargo-component" "0.21.1")
    (language "Rust" "")
  )
  (@custom "version" "0.1.0")
)
