(component $wasmi-component-example-guest
  (core type (;0;) (func (param i32 i32)))
  (core type (;1;) (func (param i32 i32 i32)))
  (core type (;2;) (func (param i32)))
  (core type (;3;) (func))
  (core type (;4;) (func (param i32 i32) (result i32)))
  (core type (;5;) (func (param i32 i32 i32 i32) (result i32)))
  (core type (;6;)
    (module
      (alias outer $wasmi-component-example-guest 0 (type (;0;)))
      (import "$root" "log" (func (type 0)))
      (alias outer $wasmi-component-example-guest 1 (type (;1;)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "list-string" (func (type 1)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "list-i32" (func (type 1)))
      (export "memory" (memory 17))
      (alias outer $wasmi-component-example-guest 2 (type (;2;)))
      (export "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-i32" (func (type 2)))
      (export "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-string" (func (type 2)))
      (alias outer $wasmi-component-example-guest 3 (type (;3;)))
      (export "init" (func (type 3)))
      (alias outer $wasmi-component-example-guest 4 (type (;4;)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#list-i32" (func (type 4)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#list-string" (func (type 4)))
      (alias outer $wasmi-component-example-guest 5 (type (;5;)))
      (export "cabi_realloc_wit_bindgen_0_58_0" (func (type 5)))
      (export "cabi_realloc" (func (type 5)))
      (export "__data_end" (global i32))
      (export "__heap_base" (global i32))
    )
  )
  (core type (;7;)
    (module
      (alias outer $wasmi-component-example-guest 0 (type (;0;)))
      (export "0" (func (type 0)))
      (alias outer $wasmi-component-example-guest 1 (type (;1;)))
      (export "1" (func (type 1)))
      (export "2" (func (type 1)))
      (export "$imports" (table 3 3 funcref))
    )
  )
  (core type (;8;)
    (module
      (alias outer $wasmi-component-example-guest 0 (type (;0;)))
      (import "" "0" (func (type 0)))
      (alias outer $wasmi-component-example-guest 1 (type (;1;)))
      (import "" "1" (func (type 1)))
      (import "" "2" (func (type 1)))
      (import "" "$imports" (table 3 3 funcref))
    )
  )
  (import "unbundled-module0" (core module (;0;) (type 6)))
  (import "unbundled-module1" (core module (;1;) (type 7)))
  (import "unbundled-module2" (core module (;2;) (type 8)))
  (type (;0;)
    (instance
      (type (;0;) (list s32))
      (type (;1;) (func (param "value" 0) (result 0)))
      (export (;0;) "list-i32" (func (type 1)))
      (type (;2;) (list string))
      (type (;3;) (func (param "value" 2) (result 2)))
      (export (;1;) "list-string" (func (type 3)))
    )
  )
  (import "wasmi-component:component-examples/round-trip@0.1.0" (instance (;0;) (type 0)))
  (type (;1;) (func (param "message" string)))
  (import "log" (func (;0;) (type 1)))
  (alias outer $wasmi-component-example-guest 0 (core module (;3;)))
  (alias outer $wasmi-component-example-guest 1 (core module (;4;)))
  (alias outer $wasmi-component-example-guest 2 (core module (;5;)))
  (core instance (;0;) (instantiate 4))
  (alias core export 0 "0" (core func (;0;)))
  (core instance (;1;)
    (export "log" (func 0))
  )
  (alias core export 0 "1" (core func (;1;)))
  (alias core export 0 "2" (core func (;2;)))
  (core instance (;2;)
    (export "list-string" (func 1))
    (export "list-i32" (func 2))
  )
  (core instance (;3;) (instantiate 3
      (with "$root" (instance 1))
      (with "wasmi-component:component-examples/round-trip@0.1.0" (instance 2))
    )
  )
  (alias core export 3 "memory" (core memory (;0;)))
  (alias core export 0 "$imports" (core table (;0;)))
  (alias core export 3 "cabi_realloc" (core func (;3;)))
  (core func (;4;) (canon lower (func 0) (memory 0) string-encoding=utf8))
  (alias export 0 "list-string" (func (;1;)))
  (core func (;5;) (canon lower (func 1) (memory 0) (realloc 3) string-encoding=utf8))
  (alias export 0 "list-i32" (func (;2;)))
  (core func (;6;) (canon lower (func 2) (memory 0) (realloc 3)))
  (core instance (;4;)
    (export "$imports" (table 0))
    (export "0" (func 4))
    (export "1" (func 5))
    (export "2" (func 6))
  )
  (core instance (;5;) (instantiate 5
      (with "" (instance 4))
    )
  )
  (type (;2;) (func))
  (alias core export 3 "init" (core func (;7;)))
  (func (;3;) (type 2) (canon lift (core func 7)))
  (export (;4;) "init" (func 3))
  (type (;3;) (list s32))
  (type (;4;) (func (param "value" 3) (result 3)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#list-i32" (core func (;8;)))
  (alias core export 3 "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-i32" (core func (;9;)))
  (func (;5;) (type 4) (canon lift (core func 8) (memory 0) (realloc 3) (post-return 9)))
  (type (;5;) (list string))
  (type (;6;) (func (param "value" 5) (result 5)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#list-string" (core func (;10;)))
  (alias core export 3 "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#list-string" (core func (;11;)))
  (func (;6;) (type 6) (canon lift (core func 10) (memory 0) (realloc 3) string-encoding=utf8 (post-return 11)))
  (component (;0;)
    (type (;0;) (list s32))
    (type (;1;) (func (param "value" 0) (result 0)))
    (import "import-func-list-i32" (func (;0;) (type 1)))
    (type (;2;) (list string))
    (type (;3;) (func (param "value" 2) (result 2)))
    (import "import-func-list-string" (func (;1;) (type 3)))
    (type (;4;) (list s32))
    (type (;5;) (func (param "value" 4) (result 4)))
    (export (;2;) "list-i32" (func 0) (func (type 5)))
    (type (;6;) (list string))
    (type (;7;) (func (param "value" 6) (result 6)))
    (export (;3;) "list-string" (func 1) (func (type 7)))
  )
  (instance (;1;) (instantiate 0
      (with "import-func-list-i32" (func 5))
      (with "import-func-list-string" (func 6))
    )
  )
  (export (;2;) "wasmi-component:component-examples/round-trip@0.1.0" (instance 1))
  (@producers
    (processed-by "wit-component" "0.227.1")
    (processed-by "cargo-component" "0.21.1")
    (language "Rust" "")
  )
  (@custom "version" "0.1.0")
)
