(component $wasmi-component-example-guest
  (core type (;0;) (func (param i32 i32) (result i32)))
  (core type (;1;) (func))
  (core type (;2;) (func (param i32) (result i32)))
  (core type (;3;) (func (param i32 i32 i32)))
  (core type (;4;) (func (param i32 i32 i32 i32)))
  (core type (;5;) (func (param i32)))
  (core type (;6;) (func (param i32 i32 i32) (result i32)))
  (core type (;7;) (func (param i32 i32 i32 i32) (result i32)))
  (core type (;8;)
    (module
      (alias outer $wasmi-component-example-guest 0 (type (;0;)))
      (import "$root" "add-import" (func (type 0)))
      (import "inline-imports" "inline-add" (func (type 0)))
      (alias outer $wasmi-component-example-guest 1 (type (;1;)))
      (import "wasmi-component:component-examples/common-funcs@0.1.0" "no-arguments" (func (type 1)))
      (alias outer $wasmi-component-example-guest 2 (type (;2;)))
      (import "wasmi-component:component-examples/common-funcs@0.1.0" "roundtrip-s32" (func (type 2)))
      (alias outer $wasmi-component-example-guest 3 (type (;3;)))
      (import "wasmi-component:component-examples/common-funcs@0.1.0" "roundtrip-string" (func (type 3)))
      (alias outer $wasmi-component-example-guest 4 (type (;4;)))
      (import "wasmi-component:component-examples/common-funcs@0.1.0" "roundtrip-multiple" (func (type 4)))
      (export "memory" (memory 17))
      (export "add-export" (func (type 0)))
      (alias outer $wasmi-component-example-guest 5 (type (;5;)))
      (export "cabi_post_wasmi-component:component-examples/common-funcs@0.1.0#roundtrip-multiple" (func (type 5)))
      (export "cabi_post_wasmi-component:component-examples/common-funcs@0.1.0#roundtrip-string" (func (type 5)))
      (export "inline-exports#inline-add" (func (type 0)))
      (export "wasmi-component:component-examples/common-funcs@0.1.0#no-arguments" (func (type 1)))
      (alias outer $wasmi-component-example-guest 6 (type (;6;)))
      (export "wasmi-component:component-examples/common-funcs@0.1.0#roundtrip-multiple" (func (type 6)))
      (export "wasmi-component:component-examples/common-funcs@0.1.0#roundtrip-s32" (func (type 2)))
      (export "wasmi-component:component-examples/common-funcs@0.1.0#roundtrip-string" (func (type 0)))
      (alias outer $wasmi-component-example-guest 7 (type (;7;)))
      (export "cabi_realloc_wit_bindgen_0_58_0" (func (type 7)))
      (export "cabi_realloc" (func (type 7)))
      (export "__data_end" (global i32))
      (export "__heap_base" (global i32))
    )
  )
  (core type (;9;)
    (module
      (alias outer $wasmi-component-example-guest 3 (type (;0;)))
      (export "0" (func (type 0)))
      (alias outer $wasmi-component-example-guest 4 (type (;1;)))
      (export "1" (func (type 1)))
      (export "$imports" (table 2 2 funcref))
    )
  )
  (core type (;10;)
    (module
      (alias outer $wasmi-component-example-guest 3 (type (;0;)))
      (import "" "0" (func (type 0)))
      (alias outer $wasmi-component-example-guest 4 (type (;1;)))
      (import "" "1" (func (type 1)))
      (import "" "$imports" (table 2 2 funcref))
    )
  )
  (import "unbundled-module0" (core module (;0;) (type 8)))
  (import "unbundled-module1" (core module (;1;) (type 9)))
  (import "unbundled-module2" (core module (;2;) (type 10)))
  (type (;0;)
    (instance
      (type (;0;) (func (param "value-a" s32) (result s32)))
      (export (;0;) "roundtrip-s32" (func (type 0)))
      (type (;1;) (func (param "value-a" string) (result string)))
      (export (;1;) "roundtrip-string" (func (type 1)))
      (type (;2;) (func (param "value-a" string) (param "value-b" s32) (result string)))
      (export (;2;) "roundtrip-multiple" (func (type 2)))
      (type (;3;) (func))
      (export (;3;) "no-arguments" (func (type 3)))
    )
  )
  (import "wasmi-component:component-examples/common-funcs@0.1.0" (instance (;0;) (type 0)))
  (type (;1;)
    (instance
      (type (;0;) (func (param "value-a" u32) (param "value-b" u32) (result u32)))
      (export (;0;) "inline-add" (func (type 0)))
    )
  )
  (import "inline-imports" (instance (;1;) (type 1)))
  (type (;2;) (func (param "value-a" u32) (param "value-b" u32) (result u32)))
  (import "add-import" (func (;0;) (type 2)))
  (alias outer $wasmi-component-example-guest 0 (core module (;3;)))
  (alias outer $wasmi-component-example-guest 1 (core module (;4;)))
  (alias outer $wasmi-component-example-guest 2 (core module (;5;)))
  (core instance (;0;) (instantiate 4))
  (core func (;0;) (canon lower (func 0)))
  (core instance (;1;)
    (export "add-import" (func 0))
  )
  (alias export 1 "inline-add" (func (;1;)))
  (core func (;1;) (canon lower (func 1)))
  (core instance (;2;)
    (export "inline-add" (func 1))
  )
  (alias export 0 "no-arguments" (func (;2;)))
  (core func (;2;) (canon lower (func 2)))
  (alias export 0 "roundtrip-s32" (func (;3;)))
  (core func (;3;) (canon lower (func 3)))
  (alias core export 0 "0" (core func (;4;)))
  (alias core export 0 "1" (core func (;5;)))
  (core instance (;3;)
    (export "no-arguments" (func 2))
    (export "roundtrip-s32" (func 3))
    (export "roundtrip-string" (func 4))
    (export "roundtrip-multiple" (func 5))
  )
  (core instance (;4;) (instantiate 3
      (with "$root" (instance 1))
      (with "inline-imports" (instance 2))
      (with "wasmi-component:component-examples/common-funcs@0.1.0" (instance 3))
    )
  )
  (alias core export 4 "memory" (core memory (;0;)))
  (alias core export 0 "$imports" (core table (;0;)))
  (alias export 0 "roundtrip-string" (func (;4;)))
  (alias core export 4 "cabi_realloc" (core func (;6;)))
  (core func (;7;) (canon lower (func 4) (memory 0) (realloc 6) string-encoding=utf8))
  (alias export 0 "roundtrip-multiple" (func (;5;)))
  (core func (;8;) (canon lower (func 5) (memory 0) (realloc 6) string-encoding=utf8))
  (core instance (;5;)
    (export "$imports" (table 0))
    (export "0" (func 7))
    (export "1" (func 8))
  )
  (core instance (;6;) (instantiate 5
      (with "" (instance 5))
    )
  )
  (alias core export 4 "add-export" (core func (;9;)))
  (func (;6;) (type 2) (canon lift (core func 9)))
  (export (;7;) "add-export" (func 6))
  (type (;3;) (func (param "value-a" s32) (result s32)))
  (alias core export 4 "wasmi-component:component-examples/common-funcs@0.1.0#roundtrip-s32" (core func (;10;)))
  (func (;8;) (type 3) (canon lift (core func 10)))
  (type (;4;) (func (param "value-a" string) (result string)))
  (alias core export 4 "wasmi-component:component-examples/common-funcs@0.1.0#roundtrip-string" (core func (;11;)))
  (alias core export 4 "cabi_post_wasmi-component:component-examples/common-funcs@0.1.0#roundtrip-string" (core func (;12;)))
  (func (;9;) (type 4) (canon lift (core func 11) (memory 0) (realloc 6) string-encoding=utf8 (post-return 12)))
  (type (;5;) (func (param "value-a" string) (param "value-b" s32) (result string)))
  (alias core export 4 "wasmi-component:component-examples/common-funcs@0.1.0#roundtrip-multiple" (core func (;13;)))
  (alias core export 4 "cabi_post_wasmi-component:component-examples/common-funcs@0.1.0#roundtrip-multiple" (core func (;14;)))
  (func (;10;) (type 5) (canon lift (core func 13) (memory 0) (realloc 6) string-encoding=utf8 (post-return 14)))
  (type (;6;) (func))
  (alias core export 4 "wasmi-component:component-examples/common-funcs@0.1.0#no-arguments" (core func (;15;)))
  (func (;11;) (type 6) (canon lift (core func 15)))
  (component (;0;)
    (type (;0;) (func (param "value-a" s32) (result s32)))
    (import "import-func-roundtrip-s32" (func (;0;) (type 0)))
    (type (;1;) (func (param "value-a" string) (result string)))
    (import "import-func-roundtrip-string" (func (;1;) (type 1)))
    (type (;2;) (func (param "value-a" string) (param "value-b" s32) (result string)))
    (import "import-func-roundtrip-multiple" (func (;2;) (type 2)))
    (type (;3;) (func))
    (import "import-func-no-arguments" (func (;3;) (type 3)))
    (type (;4;) (func (param "value-a" s32) (result s32)))
    (export (;4;) "roundtrip-s32" (func 0) (func (type 4)))
    (type (;5;) (func (param "value-a" string) (result string)))
    (export (;5;) "roundtrip-string" (func 1) (func (type 5)))
    (type (;6;) (func (param "value-a" string) (param "value-b" s32) (result string)))
    (export (;6;) "roundtrip-multiple" (func 2) (func (type 6)))
    (type (;7;) (func))
    (export (;7;) "no-arguments" (func 3) (func (type 7)))
  )
  (instance (;2;) (instantiate 0
      (with "import-func-roundtrip-s32" (func 8))
      (with "import-func-roundtrip-string" (func 9))
      (with "import-func-roundtrip-multiple" (func 10))
      (with "import-func-no-arguments" (func 11))
    )
  )
  (export (;3;) "wasmi-component:component-examples/common-funcs@0.1.0" (instance 2))
  (type (;7;) (func (param "value-a" u32) (param "value-b" u32) (result u32)))
  (alias core export 4 "inline-exports#inline-add" (core func (;16;)))
  (func (;12;) (type 7) (canon lift (core func 16)))
  (component (;1;)
    (type (;0;) (func (param "value-a" u32) (param "value-b" u32) (result u32)))
    (import "import-func-inline-add" (func (;0;) (type 0)))
    (type (;1;) (func (param "value-a" u32) (param "value-b" u32) (result u32)))
    (export (;1;) "inline-add" (func 0) (func (type 1)))
  )
  (instance (;4;) (instantiate 1
      (with "import-func-inline-add" (func 12))
    )
  )
  (export (;5;) "inline-exports" (instance 4))
  (@producers
    (processed-by "wit-component" "0.227.1")
    (processed-by "cargo-component" "0.21.1")
    (language "Rust" "")
  )
  (@custom "version" "0.1.0")
)
