(component $wasmi-component-example-guest
  (core type (;0;) (func (param i32 i32)))
  (core type (;1;) (func (param i32 i32 i32)))
  (core type (;2;) (func (param i32) (result i32)))
  (core type (;3;) (func (param f32) (result f32)))
  (core type (;4;) (func (param f64) (result f64)))
  (core type (;5;) (func (param i64) (result i64)))
  (core type (;6;) (func (param i32)))
  (core type (;7;) (func (param i32 i32) (result i32)))
  (core type (;8;) (func (param i32 i32 i32 i32) (result i32)))
  (core type (;9;)
    (module
      (alias outer $wasmi-component-example-guest 0 (type (;0;)))
      (import "$root" "log" (func (type 0)))
      (alias outer $wasmi-component-example-guest 1 (type (;1;)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "trip-string" (func (type 1)))
      (alias outer $wasmi-component-example-guest 2 (type (;2;)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "trip-s8" (func (type 2)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "trip-u8" (func (type 2)))
      (alias outer $wasmi-component-example-guest 3 (type (;3;)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "trip-f32" (func (type 3)))
      (alias outer $wasmi-component-example-guest 4 (type (;4;)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "trip-f64" (func (type 4)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "trip-s16" (func (type 2)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "trip-s32" (func (type 2)))
      (alias outer $wasmi-component-example-guest 5 (type (;5;)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "trip-s64" (func (type 5)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "trip-u16" (func (type 2)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "trip-u32" (func (type 2)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "trip-u64" (func (type 5)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "trip-bool" (func (type 2)))
      (import "wasmi-component:component-examples/round-trip@0.1.0" "trip-char" (func (type 2)))
      (export "memory" (memory 17))
      (alias outer $wasmi-component-example-guest 6 (type (;6;)))
      (export "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#trip-string" (func (type 6)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#trip-bool" (func (type 2)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#trip-char" (func (type 2)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#trip-f32" (func (type 3)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#trip-f64" (func (type 4)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#trip-s16" (func (type 2)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#trip-s32" (func (type 2)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#trip-s64" (func (type 5)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#trip-s8" (func (type 2)))
      (alias outer $wasmi-component-example-guest 7 (type (;7;)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#trip-string" (func (type 7)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#trip-u16" (func (type 2)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#trip-u32" (func (type 2)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#trip-u64" (func (type 5)))
      (export "wasmi-component:component-examples/round-trip@0.1.0#trip-u8" (func (type 2)))
      (alias outer $wasmi-component-example-guest 8 (type (;8;)))
      (export "cabi_realloc_wit_bindgen_0_58_0" (func (type 8)))
      (export "cabi_realloc" (func (type 8)))
      (export "__data_end" (global i32))
      (export "__heap_base" (global i32))
    )
  )
  (core type (;10;)
    (module
      (alias outer $wasmi-component-example-guest 0 (type (;0;)))
      (export "0" (func (type 0)))
      (alias outer $wasmi-component-example-guest 1 (type (;1;)))
      (export "1" (func (type 1)))
      (export "$imports" (table 2 2 funcref))
    )
  )
  (core type (;11;)
    (module
      (alias outer $wasmi-component-example-guest 0 (type (;0;)))
      (import "" "0" (func (type 0)))
      (alias outer $wasmi-component-example-guest 1 (type (;1;)))
      (import "" "1" (func (type 1)))
      (import "" "$imports" (table 2 2 funcref))
    )
  )
  (import "unbundled-module0" (core module (;0;) (type 9)))
  (import "unbundled-module1" (core module (;1;) (type 10)))
  (import "unbundled-module2" (core module (;2;) (type 11)))
  (type (;0;)
    (instance
      (type (;0;) (func (param "value" s8) (result s8)))
      (export (;0;) "trip-s8" (func (type 0)))
      (type (;1;) (func (param "value" s16) (result s16)))
      (export (;1;) "trip-s16" (func (type 1)))
      (type (;2;) (func (param "value" s32) (result s32)))
      (export (;2;) "trip-s32" (func (type 2)))
      (type (;3;) (func (param "value" s64) (result s64)))
      (export (;3;) "trip-s64" (func (type 3)))
      (type (;4;) (func (param "value" u8) (result u8)))
      (export (;4;) "trip-u8" (func (type 4)))
      (type (;5;) (func (param "value" u16) (result u16)))
      (export (;5;) "trip-u16" (func (type 5)))
      (type (;6;) (func (param "value" u32) (result u32)))
      (export (;6;) "trip-u32" (func (type 6)))
      (type (;7;) (func (param "value" u64) (result u64)))
      (export (;7;) "trip-u64" (func (type 7)))
      (type (;8;) (func (param "value" f32) (result f32)))
      (export (;8;) "trip-f32" (func (type 8)))
      (type (;9;) (func (param "value" f64) (result f64)))
      (export (;9;) "trip-f64" (func (type 9)))
      (type (;10;) (func (param "value" bool) (result bool)))
      (export (;10;) "trip-bool" (func (type 10)))
      (type (;11;) (func (param "value" char) (result char)))
      (export (;11;) "trip-char" (func (type 11)))
      (type (;12;) (func (param "value" string) (result string)))
      (export (;12;) "trip-string" (func (type 12)))
    )
  )
  (import "wasmi-component:component-examples/round-trip@0.1.0" (instance (;0;) (type 0)))
  (type (;1;) (func (param "message" string)))
  (import "log" (func (;0;) (type 1)))
  (alias outer $wasmi-component-example-guest 0 (core module (;3;)))
  (alias outer $wasmi-component-example-guest 1 (core module (;4;)))
  (alias outer $wasmi-component-example-guest 2 (core module (;5;)))
  (core instance (;0;) (instantiate 4))
  (alias core export 0 "0" (core func (;0;)))
  (core instance (;1;)
    (export "log" (func 0))
  )
  (alias core export 0 "1" (core func (;1;)))
  (alias export 0 "trip-s8" (func (;1;)))
  (core func (;2;) (canon lower (func 1)))
  (alias export 0 "trip-u8" (func (;2;)))
  (core func (;3;) (canon lower (func 2)))
  (alias export 0 "trip-f32" (func (;3;)))
  (core func (;4;) (canon lower (func 3)))
  (alias export 0 "trip-f64" (func (;4;)))
  (core func (;5;) (canon lower (func 4)))
  (alias export 0 "trip-s16" (func (;5;)))
  (core func (;6;) (canon lower (func 5)))
  (alias export 0 "trip-s32" (func (;6;)))
  (core func (;7;) (canon lower (func 6)))
  (alias export 0 "trip-s64" (func (;7;)))
  (core func (;8;) (canon lower (func 7)))
  (alias export 0 "trip-u16" (func (;8;)))
  (core func (;9;) (canon lower (func 8)))
  (alias export 0 "trip-u32" (func (;9;)))
  (core func (;10;) (canon lower (func 9)))
  (alias export 0 "trip-u64" (func (;10;)))
  (core func (;11;) (canon lower (func 10)))
  (alias export 0 "trip-bool" (func (;11;)))
  (core func (;12;) (canon lower (func 11)))
  (alias export 0 "trip-char" (func (;12;)))
  (core func (;13;) (canon lower (func 12)))
  (core instance (;2;)
    (export "trip-string" (func 1))
    (export "trip-s8" (func 2))
    (export "trip-u8" (func 3))
    (export "trip-f32" (func 4))
    (export "trip-f64" (func 5))
    (export "trip-s16" (func 6))
    (export "trip-s32" (func 7))
    (export "trip-s64" (func 8))
    (export "trip-u16" (func 9))
    (export "trip-u32" (func 10))
    (export "trip-u64" (func 11))
    (export "trip-bool" (func 12))
    (export "trip-char" (func 13))
  )
  (core instance (;3;) (instantiate 3
      (with "$root" (instance 1))
      (with "wasmi-component:component-examples/round-trip@0.1.0" (instance 2))
    )
  )
  (alias core export 3 "memory" (core memory (;0;)))
  (alias core export 0 "$imports" (core table (;0;)))
  (alias core export 3 "cabi_realloc" (core func (;14;)))
  (core func (;15;) (canon lower (func 0) (memory 0) string-encoding=utf8))
  (alias export 0 "trip-string" (func (;13;)))
  (core func (;16;) (canon lower (func 13) (memory 0) (realloc 14) string-encoding=utf8))
  (core instance (;4;)
    (export "$imports" (table 0))
    (export "0" (func 15))
    (export "1" (func 16))
  )
  (core instance (;5;) (instantiate 5
      (with "" (instance 4))
    )
  )
  (type (;2;) (func (param "value" s8) (result s8)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#trip-s8" (core func (;17;)))
  (func (;14;) (type 2) (canon lift (core func 17)))
  (type (;3;) (func (param "value" s16) (result s16)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#trip-s16" (core func (;18;)))
  (func (;15;) (type 3) (canon lift (core func 18)))
  (type (;4;) (func (param "value" s32) (result s32)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#trip-s32" (core func (;19;)))
  (func (;16;) (type 4) (canon lift (core func 19)))
  (type (;5;) (func (param "value" s64) (result s64)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#trip-s64" (core func (;20;)))
  (func (;17;) (type 5) (canon lift (core func 20)))
  (type (;6;) (func (param "value" u8) (result u8)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#trip-u8" (core func (;21;)))
  (func (;18;) (type 6) (canon lift (core func 21)))
  (type (;7;) (func (param "value" u16) (result u16)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#trip-u16" (core func (;22;)))
  (func (;19;) (type 7) (canon lift (core func 22)))
  (type (;8;) (func (param "value" u32) (result u32)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#trip-u32" (core func (;23;)))
  (func (;20;) (type 8) (canon lift (core func 23)))
  (type (;9;) (func (param "value" u64) (result u64)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#trip-u64" (core func (;24;)))
  (func (;21;) (type 9) (canon lift (core func 24)))
  (type (;10;) (func (param "value" f32) (result f32)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#trip-f32" (core func (;25;)))
  (func (;22;) (type 10) (canon lift (core func 25)))
  (type (;11;) (func (param "value" f64) (result f64)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#trip-f64" (core func (;26;)))
  (func (;23;) (type 11) (canon lift (core func 26)))
  (type (;12;) (func (param "value" bool) (result bool)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#trip-bool" (core func (;27;)))
  (func (;24;) (type 12) (canon lift (core func 27)))
  (type (;13;) (func (param "value" char) (result char)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#trip-char" (core func (;28;)))
  (func (;25;) (type 13) (canon lift (core func 28)))
  (type (;14;) (func (param "value" string) (result string)))
  (alias core export 3 "wasmi-component:component-examples/round-trip@0.1.0#trip-string" (core func (;29;)))
  (alias core export 3 "cabi_post_wasmi-component:component-examples/round-trip@0.1.0#trip-string" (core func (;30;)))
  (func (;26;) (type 14) (canon lift (core func 29) (memory 0) (realloc 14) string-encoding=utf8 (post-return 30)))
  (component (;0;)
    (type (;0;) (func (param "value" s8) (result s8)))
    (import "import-func-trip-s8" (func (;0;) (type 0)))
    (type (;1;) (func (param "value" s16) (result s16)))
    (import "import-func-trip-s16" (func (;1;) (type 1)))
    (type (;2;) (func (param "value" s32) (result s32)))
    (import "import-func-trip-s32" (func (;2;) (type 2)))
    (type (;3;) (func (param "value" s64) (result s64)))
    (import "import-func-trip-s64" (func (;3;) (type 3)))
    (type (;4;) (func (param "value" u8) (result u8)))
    (import "import-func-trip-u8" (func (;4;) (type 4)))
    (type (;5;) (func (param "value" u16) (result u16)))
    (import "import-func-trip-u16" (func (;5;) (type 5)))
    (type (;6;) (func (param "value" u32) (result u32)))
    (import "import-func-trip-u32" (func (;6;) (type 6)))
    (type (;7;) (func (param "value" u64) (result u64)))
    (import "import-func-trip-u64" (func (;7;) (type 7)))
    (type (;8;) (func (param "value" f32) (result f32)))
    (import "import-func-trip-f32" (func (;8;) (type 8)))
    (type (;9;) (func (param "value" f64) (result f64)))
    (import "import-func-trip-f64" (func (;9;) (type 9)))
    (type (;10;) (func (param "value" bool) (result bool)))
    (import "import-func-trip-bool" (func (;10;) (type 10)))
    (type (;11;) (func (param "value" char) (result char)))
    (import "import-func-trip-char" (func (;11;) (type 11)))
    (type (;12;) (func (param "value" string) (result string)))
    (import "import-func-trip-string" (func (;12;) (type 12)))
    (type (;13;) (func (param "value" s8) (result s8)))
    (export (;13;) "trip-s8" (func 0) (func (type 13)))
    (type (;14;) (func (param "value" s16) (result s16)))
    (export (;14;) "trip-s16" (func 1) (func (type 14)))
    (type (;15;) (func (param "value" s32) (result s32)))
    (export (;15;) "trip-s32" (func 2) (func (type 15)))
    (type (;16;) (func (param "value" s64) (result s64)))
    (export (;16;) "trip-s64" (func 3) (func (type 16)))
    (type (;17;) (func (param "value" u8) (result u8)))
    (export (;17;) "trip-u8" (func 4) (func (type 17)))
    (type (;18;) (func (param "value" u16) (result u16)))
    (export (;18;) "trip-u16" (func 5) (func (type 18)))
    (type (;19;) (func (param "value" u32) (result u32)))
    (export (;19;) "trip-u32" (func 6) (func (type 19)))
    (type (;20;) (func (param "value" u64) (result u64)))
    (export (;20;) "trip-u64" (func 7) (func (type 20)))
    (type (;21;) (func (param "value" f32) (result f32)))
    (export (;21;) "trip-f32" (func 8) (func (type 21)))
    (type (;22;) (func (param "value" f64) (result f64)))
    (export (;22;) "trip-f64" (func 9) (func (type 22)))
    (type (;23;) (func (param "value" bool) (result bool)))
    (export (;23;) "trip-bool" (func 10) (func (type 23)))
    (type (;24;) (func (param "value" char) (result char)))
    (export (;24;) "trip-char" (func 11) (func (type 24)))
    (type (;25;) (func (param "value" string) (result string)))
    (export (;25;) "trip-string" (func 12) (func (type 25)))
  )
  (instance (;1;) (instantiate 0
      (with "import-func-trip-s8" (func 14))
      (with "import-func-trip-s16" (func 15))
      (with "import-func-trip-s32" (func 16))
      (with "import-func-trip-s64" (func 17))
      (with "import-func-trip-u8" (func 18))
      (with "import-func-trip-u16" (func 19))
      (with "import-func-trip-u32" (func 20))
      (with "import-func-trip-u64" (func 21))
      (with "import-func-trip-f32" (func 22))
      (with "import-func-trip-f64" (func 23))
      (with "import-func-trip-bool" (func 24))
      (with "import-func-trip-char" (func 25))
      (with "import-func-trip-string" (func 26))
    )
  )
  (export (;2;) "wasmi-component:component-examples/round-trip@0.1.0" (instance 1))
  (@producers
    (processed-by "wit-component" "0.227.1")
    (processed-by "cargo-component" "0.21.1")
    (language "Rust" "")
  )
  (@custom "version" "0.1.0")
)
