package wasmi-component:component-examples@0.1.0;

interface round-trip {
    trip-s8: func(value: s8) -> s8;
    trip-s16: func(value: s16) -> s16;
    trip-s32: func(value: s32) -> s32;
    trip-s64: func(value: s64) -> s64;

    trip-u8: func(value: u8) -> u8;
    trip-u16: func(value: u16) -> u16;
    trip-u32: func(value: u32) -> u32;
    trip-u64: func(value: u64) -> u64;

    trip-f32: func(value: f32) -> f32;
    trip-f64: func(value: f64) -> f64;

    trip-bool: func(value: bool) -> bool;
    trip-char: func(value: char) -> char;
    trip-string: func(value: string) -> string;
}

world test-example {
    import round-trip;

    export round-trip;

    import log: func(message: string);
}
