package wasmi-component:component-examples@0.1.0;

interface common-funcs {
    roundtrip-s32: func(value-a: s32) -> s32;
    
    roundtrip-string: func(value-a: string) -> string;

    roundtrip-multiple: func(value-a: string, value-b: s32) -> string;

    no-arguments: func();
}

world test-example {
    export common-funcs;

    import common-funcs;

    export add-export: func(value-a: u32, value-b: u32) -> u32;

    import add-import: func(value-a: u32, value-b: u32) -> u32;

    export inline-exports: interface {
        inline-add: func(value-a: u32, value-b: u32) -> u32;
    }

    import inline-imports: interface {
        inline-add: func(value-a: u32, value-b: u32) -> u32;
    }
}
